/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119431-gf4e72eb5a3-20250505"
#endif /* AVUTIL_FFVERSION_H */
